# Makefile.x86_64 -- native build of Main_MiSTeX for an x86-64 Linux host that
# reaches the FPGA over PCIe (FPGA-Retro: Varium C1100 / FK33 with the LitePCIe
# endpoint and the `hps` CSR bridge).  Selects fpga_io_pcie.cpp with
# -DPCIE_HOST; the SPI + GPIO backend in fpga_io.cpp is compiled out.
#
#   make -f Makefile.x86_64 -j
#
# Differences from the Raspberry Pi Makefile: host gcc; no libgpiod and no
# spidev needed at link time; libco's amd64 backend; Imlib2 replaced by
# lib/imlib2_stub (no libImlib2 on this host -- swap IMLIB2_SRC/IMLIB2_LIB
# below when the real library and its headers are installed).
SHELL = /bin/bash -o pipefail

CC      = gcc
LD      = ld
STRIP   = strip

ifeq ($(V),1)
	Q :=
else
	Q := @
endif

INCLUDE	= -I./
INCLUDE	+= -I./lib/libco
INCLUDE	+= -I./lib/miniz
INCLUDE	+= -I./lib/md5
INCLUDE += -I./lib/lzma
INCLUDE += -I./lib/libchdr/include
INCLUDE += -I./lib/flac/include
INCLUDE += -I./lib/flac/src/include
INCLUDE += -I./lib/bluetooth

# Imlib2: stub until the host has libImlib2-dev; then set
#   IMLIB2_SRC =            IMLIB2_LIB = -lImlib2
IMLIB2_SRC = $(wildcard ./lib/imlib2_stub/*.c)
IMLIB2_LIB =
# Bluetooth: stub (no libbluetooth on this host); with libbluetooth-dev set
#   BT_SRC =                BT_LIB = -lbluetooth
BT_SRC = $(wildcard ./lib/host_stubs/*.c)
BT_LIB =
# zlib (support/uef): the runtime library is present, the dev symlink is not
ZLIB_LIB = -l:libz.so.1

PRJ = MiSTer
C_SRC =   $(wildcard *.c) \
          $(wildcard ./lib/miniz/*.c) \
          $(wildcard ./lib/md5/*.c) \
          $(wildcard ./lib/lzma/*.c) \
          $(wildcard ./lib/flac/src/*.c) \
          $(wildcard ./lib/libchdr/*.c) \
          $(IMLIB2_SRC) $(BT_SRC) \
          lib/libco/libco.c

CPP_SRC = $(wildcard *.cpp) \
          arm/scheduler.cpp \
          $(wildcard ./support/*/*.cpp)

IMG =     $(wildcard *.png)

OBJ	= $(C_SRC:.c=.c.o) $(CPP_SRC:.cpp=.cpp.o) $(IMG:.png=.png.o)
DEP	= $(C_SRC:.c=.c.d) $(CPP_SRC:.cpp=.cpp.d)

DFLAGS	= $(INCLUDE) -DPCIE_HOST -D_7ZIP_ST -DPACKAGE_VERSION=\"1.3.3\" -DUSE_SCHEDULER -DFLAC_API_EXPORTS -DFLAC__HAS_OGG=0 -DHAVE_LROUND -DHAVE_STDINT_H -DHAVE_STDLIB_H -DHAVE_SYS_PARAM_H -DENABLE_64_BIT_WORDS=0 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -DVDATE=\"`date +"%y%m%d"`\"
CFLAGS	= $(DFLAGS) -w -Wextra -Wno-strict-aliasing -Wno-stringop-overflow -Wno-stringop-truncation -Wno-format-truncation -Wno-psabi -Wno-restrict -c -O2 $(DEBUG)
LFLAGS	= -lstdc++ -lm -lrt -lpthread $(IMLIB2_LIB) $(BT_LIB) $(ZLIB_LIB)

ifeq ($(PROFILING),1)
	DFLAGS += -DPROFILING
endif

all: $(PRJ)

$(PRJ): $(OBJ)
	$(Q)$(info $@)
	$(Q)$(CC) -o $@ $+ $(LFLAGS)
	$(Q)cp $@ $@.elf
	$(Q)$(STRIP) $@

.PHONY: clean
clean:
	$(Q)rm -f *.elf *.map *.lst *.user *~ $(PRJ)
	$(Q)find . \( -name '*.o' -o -name '*.d' -o -name '*.bak' -o -name '*.rej' -o -name '*.org' \) -exec rm -f {} \;

%.c.o: %.c
	$(Q)$(info $<)
	$(Q)$(CC) $(CFLAGS) -std=gnu99 -o $@ -c $< 2>&1 | sed -e 's/\(.[a-zA-Z]\+\):\([0-9]\+\):\([0-9]\+\):/\1(\2,\ \3):/g'

%.cpp.o: %.cpp
	$(Q)$(info $<)
	$(Q)$(CC) $(CFLAGS) -std=gnu++14 -Wno-class-memaccess -o $@ -c $< 2>&1 | sed -e 's/\(.[a-zA-Z]\+\):\([0-9]\+\):\([0-9]\+\):/\1(\2,\ \3):/g'

%.png.o: %.png
	$(Q)$(info $<)
	$(Q)$(LD) -r -b binary -o $@ $< 2>&1 | sed -e 's/\(.[a-zA-Z]\+\):\([0-9]\+\):\([0-9]\+\):/\1(\2,\ \3):/g'

ifneq ($(MAKECMDGOALS), clean)
-include $(DEP)
endif
%.c.d: %.c
	$(Q)$(CC) $(DFLAGS) -MM $< -MT $@ -MT $*.c.o -MF $@ 2>&1 | sed -e 's/\(.[a-zA-Z]\+\):\([0-9]\+\):\([0-9]\+\):/\1(\2,\ \3):/g'

%.cpp.d: %.cpp
	$(Q)$(CC) $(DFLAGS) -MM $< -MT $@ -MT $*.cpp.o -MF $@ 2>&1 | sed -e 's/\(.[a-zA-Z]\+\):\([0-9]\+\):\([0-9]\+\):/\1(\2,\ \3):/g'

# Ensure correct time stamp
main.cpp.o: $(filter-out main.cpp.o, $(OBJ))
